//READ CRUD
export const ALL_ADOPTER_REQUEST = 'ALL_ADOPTER_REQUEST'
export const ALL_ADOPTER_SUCCESS = 'ALL_ADOPTER_SUCCESS'
export const ALL_ADOPTER_FAIL = 'ALL_ADOPTER_FAIL'

//CREATE
export const NEW_ADOPTER_REQUEST = 'NEW_ADOPTER_REQUEST'
export const NEW_ADOPTER_SUCCESS = 'NEW_ADOPTER_SUCCESS'
export const NEW_ADOPTER_RESET = 'NEW_ADOPTER_RESET'
export const NEW_ADOPTER_FAIL = 'NEW_ADOPTER_FAIL'


//UPDATE CRUD
export const UPDATE_ADOPTER_REQUEST = 'UPDATE_ADOPTER_REQUEST'
export const UPDATE_ADOPTER_SUCCESS = 'UPDATE_ADOPTER_SUCCESS'
export const UPDATE_ADOPTER_RESET = 'UPDATE_ADOPTER_RESET'
export const UPDATE_ADOPTER_FAIL = 'UPDATE_ADOPTER_FAIL'

export const ADOPTER_DETAILS_REQUEST = 'ADOPTER_DETAILS_REQUEST'
export const ADOPTER_DETAILS_SUCCESS = 'ADOPTER_DETAILS_SUCCESS'
export const ADOPTER_DETAILS_FAIL = 'ADOPTER_DETAILS_FAIL'

//DELETE
export const DELETE_ADOPTER_REQUEST = 'DELETE_ADOPTER_REQUEST'
export const DELETE_ADOPTER_SUCCESS = 'DELETE_ADOPTER_SUCCESS'
export const DELETE_ADOPTER_RESET = 'DELETE_ADOPTER_RESET'
export const DELETE_ADOPTER_FAIL = 'DELETE_ADOPTER_FAIL'





export const CLEAR_ERRORS = 'CLEAR_ERRORS'
