//Front
export const ALL_ANIMALS_REQUEST = 'ALL_ANIMALS_REQUEST'
export const ALL_ANIMALS_SUCCESS = 'ALL_ANIMALS_SUCCESS'
export const ALL_ANIMALS_FAIL = 'ALL_ANIMALS_FAIL'


//Animal Detail
export const ANIMALS_DETAILS_REQUEST = 'ANIMALS_DETAILS_REQUEST' 
export const ANIMALS_DETAILS_SUCCESS = 'ANIMALS_DETAILS_SUCCESS'
export const ANIMALS_DETAILS_FAIL = 'ANIMALS_DETAILS_FAIL'



//READ
export const ALL_ADMIN_ANIMALS_REQUEST = 'ALL_ADMIN_ANIMALS_REQUEST'
export const ALL_ADMIN_ANIMALS_SUCCESS = 'ALL_ADMIN_ANIMALS_SUCCESS'
export const ALL_ADMIN_ANIMALS_FAIL = 'ALL_ADMIN_ANIMALS_FAIL'


//CREATE
export const NEW_ANIMAL_REQUEST = 'NEW_ANIMAL_REQUEST'
export const NEW_ANIMAL_SUCCESS = 'NEW_ANIMAL_SUCCESS'
export const NEW_ANIMAL_RESET = 'NEW_ANIMAL_RESET'
export const NEW_ANIMAL_FAIL = 'NEW_ANIMAL_FAIL'


//UPDATE
export const UPDATE_ANIMAL_REQUEST = 'UPDATE_ANIMAL_REQUEST'
export const UPDATE_ANIMAL_SUCCESS = 'UPDATE_ANIMAL_SUCCESS'
export const UPDATE_ANIMAL_RESET = 'UPDATE_ANIMAL_RESET'
export const UPDATE_ANIMAL_FAIL = 'UPDATE_ANIMAL_FAIL'

//INFO
export const ANIMAL_INFO_REQUEST = 'ANIMAL_INFO_REQUEST'
export const ANIMAL_INFO_SUCCESS = 'ANIMAL_INFO_SUCCESS'
export const ANIMAL_INFO_FAIL = 'ANIMAL_INFO_FAIL'

//DELETE CRUD
export const DELETE_ANIMAL_REQUEST = 'DELETE_ANIMAL_REQUEST'
export const DELETE_ANIMAL_SUCCESS = 'DELETE_ANIMAL_SUCCESS'
export const DELETE_ANIMAL_RESET = 'DELETE_ANIMAL_RESET'
export const DELETE_ANIMAL_FAIL = 'DELETE_ANIMAL_FAIL'



//REVIEW
export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'
