


export const ALL_INJURYDISEASE_REQUEST = 'ALL_INJURYDISEASE_REQUEST'
export const ALL_INJURYDISEASE_SUCCESS = 'ALL_INJURYDISEASE_SUCCESS'
export const ALL_INJURYDISEASE_FAIL = 'ALL_INJURYDISEASE_FAIL'


export const NEW_INJURYDISEASE_REQUEST = 'NEW_INJURYDISEASE_REQUEST'
export const NEW_INJURYDISEASE_SUCCESS = 'NEW_INJURYDISEASE_SUCCESS'
export const NEW_INJURYDISEASE_RESET = 'NEW_INJURYDISEASE_RESET'
export const NEW_INJURYDISEASE_FAIL = 'NEW_INJURYDISEASE_FAIL'


export const UPDATE_INJURYDISEASE_REQUEST = 'UPDATE_INJURYDISEASE_REQUEST'
export const UPDATE_INJURYDISEASE_SUCCESS = 'UPDATE_INJURYDISEASE_SUCCESS'
export const UPDATE_INJURYDISEASE_RESET = 'UPDATE_INJURYDISEASE_RESET'
export const UPDATE_INJURYDISEASE_FAIL = 'UPDATE_INJURYDISEASE_FAIL'

export const INJURYDISEASE_DETAILS_REQUEST = 'INJURYDISEASE_DETAILS_REQUEST'
export const INJURYDISEASE_DETAILS_SUCCESS = 'INJURYDISEASE_DETAILS_SUCCESS'
export const INJURYDISEASE_DETAILS_FAIL = 'INJURYDISEASE_DETAILS_FAIL'

export const DELETE_INJURYDISEASE_REQUEST = 'DELETE_INJURYDISEASE_REQUEST'
export const DELETE_INJURYDISEASE_SUCCESS = 'DELETE_INJURYDISEASE_SUCCESS'
export const DELETE_INJURYDISEASE_RESET = 'DELETE_INJURYDISEASE_RESET'
export const DELETE_INJURYDISEASE_FAIL = 'DELETE_INJURYDISEASE_FAIL'






export const CLEAR_ERRORS = 'CLEAR_ERRORS'
