//READ CRUD
export const ALL_PERSONNEL_REQUEST = 'ALL_PERSONNEL_REQUEST'
export const ALL_PERSONNEL_SUCCESS = 'ALL_PERSONNEL_SUCCESS'
export const ALL_PERSONNEL_FAIL = 'ALL_PERSONNEL_FAIL'



//CREATE
export const NEW_PERSONNEL_REQUEST = 'NEW_PERSONNEL_REQUEST'
export const NEW_PERSONNEL_SUCCESS = 'NEW_PERSONNEL_SUCCESS'
export const NEW_PERSONNEL_RESET = 'NEW_PERSONNEL_RESET'
export const NEW_PERSONNEL_FAIL = 'NEW_PERSONNEL_FAIL'


//UPDATE CRUD
export const UPDATE_PERSONNEL_REQUEST = 'UPDATE_PERSONNEL_REQUEST'
export const UPDATE_PERSONNEL_SUCCESS = 'UPDATE_PERSONNEL_SUCCESS'
export const UPDATE_PERSONNEL_RESET = 'UPDATE_PERSONNEL_RESET'
export const UPDATE_PERSONNEL_FAIL = 'UPDATE_PERSONNEL_FAIL'

export const PERSONNEL_DETAILS_REQUEST = 'PERSONNEL_DETAILS_REQUEST'
export const PERSONNEL_DETAILS_SUCCESS = 'PERSONNEL_DETAILS_SUCCESS'
export const PERSONNEL_DETAILS_FAIL = 'PERSONNEL_DETAILS_FAIL'


//DELETE CRUD
export const DELETE_PERSONNEL_REQUEST = 'DELETE_PERSONNEL_REQUEST'
export const DELETE_PERSONNEL_SUCCESS = 'DELETE_PERSONNEL_SUCCESS'
export const DELETE_PERSONNEL_RESET = 'DELETE_PERSONNEL_RESET'
export const DELETE_PERSONNEL_FAIL = 'DELETE_PERSONNEL_FAIL'


export const CLEAR_ERRORS = "CLEAR_ERRORS"